export const CONDENSED_TEXT_BREAKPOINT = 350;
export const TOUCH_INPUT_BREAKPOINT = 400;
export const MENU_BREAKPOINT = 480;
export const MENU_ABOUT_HIDE_BREAKPOINT = 570;
export const MENU_SHORTEN_NAMES_BREAKPOINT = 635;
export const ASIDE_BREAKPOINT = 800;
export const CENTERING_BREAKPOINT = 960;
