export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const STARTED_COLLABORATION = 'STARTED_COLLABORATION';
export const JOINED_COLLABORATION = 'JOINED_COLLABORATION';
export const REQUEST_COLLABORATION_STATUS = 'REQUEST_COLLABORATION_STATUS';
export const RECEIVED_COLLABORATION_STATUS = 'RECEIVED_COLLABORATION_STATUS';
export const RECORD_ANSWER = 'RECORD_ANSWER';
export const GOTO_PREVIOUS_QUESTION = 'GOTO_PREVIOUS_QUESTION';
export const GOTO_NEXT_QUESTION = 'GOTO_NEXT_QUESTION';
export const SUBMIT_QUESTIONNAIRE = 'SUBMIT_QUESTIONNAIRE';
export const REQUEST_SCRAMBLED_RESULT = 'REQUEST_SCRAMBLED_RESULT';
export const RECEIVED_SCRAMBLED_RESULT = 'RECEIVED_SCRAMBLED_RESULT';
export const REQUEST_REDIRECT = 'REQUEST_REDIRECT';
export const RESET_REDIRECT = 'RESET_REDIRECT';
export const API_CALL_STARTED = 'API_CALL_STARTED';
export const API_CALL_FINISHED = 'API_CALL_FINISHED';