export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const REQUEST_REDIRECT = 'REQUEST_REDIRECT';
export const RESET_REDIRECT = 'RESET_REDIRECT';

export const START_COLLABORATION = 'START_COLLABORATION';
export const JOIN_COLLABORATION = 'JOIN_COLLABORATION';
export const GET_COLLABORATION_STATUS = 'COLLABORATION_STATUS';
export const GET_SCRAMBLED_RESULT = 'GET_SCRAMBLED_RESULT';

export const RECORD_ANSWER = 'RECORD_ANSWER';
export const GOTO_PREVIOUS_QUESTION = 'GOTO_PREVIOUS_QUESTION';
export const GOTO_NEXT_QUESTION = 'GOTO_NEXT_QUESTION';
export const SUBMIT_QUESTIONNAIRE = 'SUBMIT_QUESTIONNAIRE';

export const API_CALL_STARTED = 'API_CALL_STARTED';
export const API_CALL_FINISHED = 'API_CALL_FINISHED';