export const API_CALL_STARTED = 'API_CALL_STARTED';
export const API_CALL_FINISHED = 'API_CALL_FINISHED';
export const WINDOW_RESIZED = 'WINDOW_RESIZED';

export const REQUEST_REDIRECT = 'REQUEST_REDIRECT';
export const RESET_REDIRECT = 'RESET_REDIRECT';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_RESPONSE = 'SIGNIN_RESPONSE';
export const SIGNOUT = 'SIGNOUT';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_RESPONSE = 'RESET_PASSWORD_RESPONSE';

export const START_COLLABORATION_REQUEST = 'START_COLLABORATION_REQUEST';
export const START_COLLABORATION_RESPONSE = 'START_COLLABORATION_RESPONSE';
export const JOIN_COLLABORATION_REQUEST = 'JOIN_COLLABORATION_REQUEST';
export const JOIN_COLLABORATION_RESPONSE = 'JOIN_COLLABORATION_RESPONSE';
export const RECORD_ANSWER = 'RECORD_ANSWER';
export const AUTO_PICK_ANSWER = 'AUTO_PICK_ANSWER';
export const GOTO_PREVIOUS_QUESTION = 'GOTO_PREVIOUS_QUESTION';
export const GOTO_NEXT_QUESTION = 'GOTO_NEXT_QUESTION';
export const SUBMIT_QUESTIONNAIRE_REQUEST = 'SUBMIT_QUESTIONNAIRE_REQUEST';
export const SUBMIT_QUESTIONNAIRE_RESPONSE = 'SUBMIT_QUESTIONNAIRE_RESPONSE';
export const GET_COLLABORATION_STATUS_REQUEST = 'GET_COLLABORATION_STATUS_REQUEST';
export const GET_COLLABORATION_STATUS_RESPONSE = 'GET_COLLABORATION_STATUS_RESPONSE';
export const FORCE_COLLABORATION_END_REQUEST = 'FORCE_COLLABORATION_END_REQUEST';
export const FORCE_COLLABORATION_END_RESPONSE = 'FORCE_COLLABORATION_END_RESPONSE';
export const FORCED_COLLABORATION_END = 'FORCED_COLLABORATION_END';
export const GET_SCRAMBLED_REQUEST = 'GET_SCRAMBLED_REQUEST';
export const GET_SCRAMBLED_RESPONSE = 'GET_SCRAMBLED_RESPONSE';

